### PR TITLE
setup poetry and move to github actions

### PR DESCRIPTION
**Pull request by zaro0508**
Update with files from the sceptre-template-handler-template[1] repo to update this project to use poetry and github actions CI

[1] https://github.com/Sceptre/sceptre-template-handler-template

### CODE REVIEW

**Comment by zaro0508** [comment]
test is failing on a `assert_called_once_with` check, however pytest reports that the exected and actual calls are identical...

```
expected = call('', (<StackLoggerAdapter sceptre.template_handlers (WARNING)>, <Mock spec='ConnectionManager' id='4695147136'>, {'file_asset_bucket_name': 'my_bucket'}, <MagicMock name='mock().import_class()' id='4695462528'>), {})
actual = call('', (<StackLoggerAdapter sceptre.template_handlers (WARNING)>, <Mock spec='ConnectionManager' id='4695147136'>, {'file_asset_bucket_name': 'my_bucket'}, <MagicMock name='mock().import_class()' id='4695462528'>), {})
```

**Comment by zaro0508** [comment]
interesting, it looks like the build for this handler never actually passed on circleci https://app.circleci.com/pipelines/github/Sceptre/sceptre-cdk-handler

**Comment by zaro0508** [comment]
Merging in since tests never actually passed when it was initially implemented.   Will let whomever is interested to fix up the tests.

**Comment by ericabrauer** [comment]
Do we have a new issue for the tests? I just saw we have a bunch of things closing out and was checking to see if this was already done (I've been trying to tinker with it but it's been slow going)

**Pull request merged**
